/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : font-name
 #	author : miyako
 #	2017/05/18
 #
 # --------------------------------------------------------------------------------*/



// --- Font
void FONT_Convert_name(sLONG_PTR *pResult, PackagePtr pParams);
